name: preHugo
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *" #runs at 10:00 UTC every 1st day of month
    
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
            python-version: 3.9 #install the python needed
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run
        run: |
          python run.py
          python createpages.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "newMap"
          git push
